version: "3.8"
services:
  gomoku-db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=leblanc
    volumes:
      - db:/var/lib/mysql
  gomoku-web:
    image: gomoku-web:1.0.0
    depends_on:
      - gomoku-db
      - gomoku-engine
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://gomoku-db:3306/root?useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=leblanc
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - FR_LEBLANC_GOMOKU_ENGINEURL=http://gomoku-engine
      - SPRING_PROFILES_ACTIVE=sso
  gomoku-engine:
    image: gomoku-engine:1.0.0
  gomoku-engine-http:
    image: gomoku-engine-http:1.0.0
    ports:
      - 80:80
  gomoku-ids:
    image: quay.io/keycloak/keycloak:25.0.4
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8282:8080
#    command: start-dev --spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true
    command: start-dev
    volumes:
     - ids:/opt/keycloak/data
volumes:
  db:
  ids: