version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=leblanc
    volumes:
      - db:/var/lib/mysql
  gomoku-web:
    image: gomoku-web:1.0.0
    depends_on:
      - mysqldb
    ports:
      - ${WEB_PORT}:${WEB_PORT}
      - ${WEB_DEBUG_PORT}:${WEB_DEBUG_PORT}
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/root?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "leblanc",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "fr.leblanc.gomoku.engineUrl" : "http://gomoku-engine:${ENGINE_PORT}"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  gomoku-engine:
    image: gomoku-engine:1.0.0
    environment:
      SPRING_APPLICATION_JSON: '{
        "server.port" : "${ENGINE_PORT}"
        }'
    ports:
      - ${ENGINE_PORT}:${ENGINE_PORT}
      - ${ENGINE_DEBUG_PORT}:${ENGINE_DEBUG_PORT}
    stdin_open: true
    tty: true
volumes:
  db: