version: "3.8"
services:
  gomoku-db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=leblanc
    volumes:
      - db:/var/lib/mysql
    ports:
      - 33066:3306
  gomoku-web:
    image: europe-west1-docker.pkg.dev/gomoku-375720/gomoku-web/gomoku-web:1.0
    depends_on:
      - gomoku-db
      - gomoku-engine
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://gomoku-db:3306/root?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "leblanc",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "fr.leblanc.gomoku.engineUrl" : "http://gomoku-engine:8081"
        }'
  gomoku-engine:
    image: europe-west1-docker.pkg.dev/gomoku-375720/gomoku-engine/gomoku-engine:1.0
    ports:
      - 8081:8081
volumes:
  db: