version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=leblanc
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
  gomoku:
    image: gomoku:0.0.1-SNAPSHOT
    depends_on:
      - mysqldb
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/root?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "leblanc",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "fr.leblanc.gomoku.engineUrl" : "http://gomoku-engine:9000"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  gomoku-engine:
    image: gomoku-engine:0.0.1-SNAPSHOT
    ports:
      - 9000:9000
    stdin_open: true
    tty: true
volumes:
  db: