version: "3.8"
services:
  gomoku-db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=leblanc
    volumes:
      - db:/var/lib/mysql
  gomoku-web:
    image: gomoku-web:1.0.0
    depends_on:
      - gomoku-db
      - gomoku-engine
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://gomoku-db:3306/root?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "leblanc",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "fr.leblanc.gomoku.engineUrl" : "http://gomoku-engine.leblanc.fr"
        }'
  gomoku-engine:
    image: gomoku-engine:1.0.0
  gomoku-engine-http:
    image: gomoku-engine-http:1.0.0
    ports:
      - 80:80
volumes:
  db: