
package fr.leblanc.gomoku.model;

public enum MessageType
{
    MOVE,
    EVALUATION,
    REFRESH_BOARD,
    LAST_MOVE,
	IS_WIN,
	IS_COMPUTING,
	CHALLENGE_ACCEPTED,
	CHALLENGE_DECLINED,
	ONLINE_GAME_ABORTED,
	USER_CONNECTED,
	USER_DISCONNECTED,
	NEW_CHALLENGER
}