
package fr.leblanc.gomoku.model;

public enum MessageType
{
    MOVE,
    EVALUATION,
    REFRESH_BOARD,
    LAST_MOVE,
	IS_WIN,
	IS_COMPUTING,
	NEW_CHALLENGE,
	CHALLENGE_DECLINED,
	CHALLENGE_ACCEPTED,
	ONLINE_GAME_ABORTED,
	CONNECTED_USER,
	DISCONNECTED_USER;
}